### ISSUE TITLE
Support for VM that isn't in Azure

### ISSUE THREAD

**Issue by bostrowski13** [TraGicCode/tragiccode-azure_key_vault#4]
So does this support a VM that is running as your Puppet Master that isn't in Azure?  If so, is there any documentation on this?

**Comment by turbodog** [comment]
@bostrowski13 acknowledging that this doesn't answer your question, in Puppet 6 agents will be able to use functions like this so any Puppet-managed VM in Azure could fetch secrets from Key Vault.

**Comment by TraGicCode** [comment]
Hey @bostrowski13 ,

Unfortunately the puppetmaster will need to live on azure since this utilizes azure Managed Service Identity ( MSI ).  

However, as @turbodog stated, when puppet agent v6 is released the agents themselves will be able to pull secrets using the new Deferred mechanism.  This has been tested and does indeed work.  Until then we most wait.  We will provide some documentation on using the Deferred mechanism to help others figure out how to call the function correctly in code once puppet v6 is released.

**Comment by bostrowski13** [comment]
thanks for the info all.  need to hope that puppet 6 release date is soon ...or at least sooner than later.

**Comment by turbodog** [comment]
Puppet 6 should launch sometime in September so not too long

**Comment by AMoghrabi** [comment]
Hey @TraGicCode , quick question for you. Now that Puppet 6 is released, I'm curious how this works. Our master puppet node is not in Azure -- it's running on-prem.

To be clear, can we still use this if our master and slave nodes are on-prem but are running Puppet version 6+?

Thanks for your help!
